name: Aprendiendo GitHub Actions #Nombre del workflow
run-name: ${{ github.actor }} is learning GitHub Actions
on: [push] #evento que lo activará
jobs: #Definición de los jobs
  hola-mundo: #Nombre del job
    runs-on: ubuntu-latest #Maquina en la que correrá
    container: node:18
    steps: #Lista de steps del job hola-mundo
      - uses: actions/setup-node@v3
      - name: Run index
        run: node index.js