name: Aprendiendo GitHub Actions #Nombre del workflow
on: 
  push: #evento que lo activará
    branches: #rama en donde se activara el evento
    - main
jobs: #Definición de los jobs
  hola-mundo: #Nombre del job
    runs-on: ubuntu-latest #Maquina en la que correrá
    container: node:18
    steps: #Lista de steps del job hola-mundo
      - uses: actions/setup-node@v4
      - name: Run index
        run: node index.js